import type { MenuCategoryId, MenuItem } from "./types";

// Display order for the tabs on /carte.
export const menuCategories: MenuCategoryId[] = [
  "espresso",
  "degustation",
  "froid",
  "signatures",
  "sans-cafe",
  "fraicheur",
  "douceurs",
  "sale",
  "formules",
];

export const menu: MenuItem[] = [
  // --- espresso — Espresso & lait ---
  {
    id: "espresso",
    category: "espresso",
    name: { fr: "Espresso", en: "Espresso", hy: "Էսպրեսո" },
    description: {
      fr: "Un shot pur, extraction précise à 93 °C.",
      en: "A pure shot, precisely pulled at 93°C.",
      hy: "Մաքուր շոթ՝ ճշգրիտ էքստրակցիա 93°C-ում։",
    },
    price: 3.0,
    tempC: 93,
    tags: ["decafAvailable"],
  },
  {
    id: "double-espresso",
    category: "espresso",
    name: { fr: "Double espresso", en: "Double espresso", hy: "Կրկնակի էսպրեսո" },
    description: {
      fr: "Deux shots, même précision.",
      en: "Two shots, same precision.",
      hy: "Երկու շոթ, նույն ճշգրտությամբ։",
    },
    price: 3.8,
    tempC: 93,
    tags: ["decafAvailable"],
  },
  {
    id: "americano",
    category: "espresso",
    name: { fr: "Americano", en: "Americano", hy: "Ամերիկանո" },
    description: {
      fr: "Espresso allongé à l'eau chaude, tout en rondeur.",
      en: "Espresso lengthened with hot water, smooth and round.",
      hy: "Էսպրեսո՝ նոսրացված տաք ջրով, փափուկ համով։",
    },
    price: 4.0,
    tags: ["decafAvailable"],
  },
  {
    id: "cortado",
    category: "espresso",
    name: { fr: "Cortado", en: "Cortado", hy: "Կորտադո" },
    description: {
      fr: "Espresso coupé d'un nuage de lait chaud.",
      en: "Espresso cut with a splash of warm milk.",
      hy: "Էսպրեսո՝ մի պուտ տաք կաթով։",
    },
    price: 4.2,
    tags: ["decafAvailable"],
  },
  {
    id: "flat-white",
    category: "espresso",
    name: { fr: "Flat white", en: "Flat white", hy: "Ֆլեթ վայթ" },
    description: {
      fr: "Double ristretto, lait micro-mousse, texture soyeuse.",
      en: "Double ristretto, microfoam milk, silky texture.",
      hy: "Կրկնակի ռիստրետտո, միկրոփրփուր կաթ, մետաքսանման հյուսվածք։",
    },
    price: 5.0,
    tempC: 65,
    tags: ["decafAvailable"],
  },
  {
    id: "cappuccino",
    category: "espresso",
    name: { fr: "Cappuccino", en: "Cappuccino", hy: "Կապուչինո" },
    description: {
      fr: "Espresso, lait vapeur et mousse en équilibre parfait.",
      en: "Espresso, steamed milk and foam in perfect balance.",
      hy: "Էսպրեսո, շոգեխաշված կաթ և փրփուր՝ կատարյալ հավասարակշռությամբ։",
    },
    price: 5.0,
    tempC: 65,
    tags: ["decafAvailable"],
  },
  {
    id: "latte",
    category: "espresso",
    name: { fr: "Latte", en: "Latte", hy: "Լատտե" },
    description: {
      fr: "Espresso tout en douceur, généreux voile de lait.",
      en: "Espresso at its softest, a generous veil of milk.",
      hy: "Փափուկ էսպրեսո՝ առատ կաթի շերտով։",
    },
    price: 5.5,
    tempC: 65,
    tags: ["decafAvailable"],
  },
  {
    id: "mocha",
    category: "espresso",
    name: { fr: "Mocha", en: "Mocha", hy: "Մոկա" },
    description: {
      fr: "Espresso, chocolat fondant et lait vapeur.",
      en: "Espresso, melting chocolate and steamed milk.",
      hy: "Էսպրեսո, հալվող շոկոլադ և շոգեխաշված կաթ։",
    },
    price: 6.0,
    tags: ["decafAvailable"],
  },
  {
    id: "lait-vegetal",
    category: "espresso",
    name: {
      fr: "Lait végétal (avoine, amande, soja)",
      en: "Plant-based milk (oat, almond, soy)",
      hy: "Բուսական կաթ (վարսակ, նուշ, սոյա)",
    },
    description: {
      fr: "En option sur toutes nos boissons lactées.",
      en: "Available on any of our milk-based drinks.",
      hy: "Հասանելի է բոլոր կաթնային խմիչքների հետ։",
    },
    price: 0.5,
    tags: ["vegan"],
    supplement: true,
  },

  // --- degustation — Bar à dégustation ---
  {
    id: "v60",
    category: "degustation",
    name: {
      fr: "V60 — origine au choix",
      en: "V60 — single origin of your choice",
      hy: "V60 — ըստ ընտրած ծագման",
    },
    description: {
      fr: "Filtre V60, sur l'origine de votre choix.",
      en: "V60 filter, brewed to order from the origin you pick.",
      hy: "V60 զտիչ՝ ըստ Ձեր ընտրած ծագման։",
    },
    price: [6, 9],
    tags: ["decafAvailable"],
  },
  {
    id: "aeropress",
    category: "degustation",
    name: { fr: "AeroPress", en: "AeroPress", hy: "ԱերոՊրես" },
    description: {
      fr: "Extraction douce sous pression, tasse nette et ronde.",
      en: "Gentle pressure brew, a clean, round cup.",
      hy: "Մեղմ ճնշումով եփում, մաքուր և կլոր բաժակ։",
    },
    price: [6, 8],
    tags: ["decafAvailable"],
  },
  {
    id: "siphon",
    category: "degustation",
    name: { fr: "Siphon", en: "Siphon", hy: "Սիֆոն" },
    description: {
      fr: "Préparation-spectacle au vide, en salle.",
      en: "A vacuum-brew show, made tableside.",
      hy: "Վակուումային եփում՝ ներկայացման տեսքով, սեղանի մոտ։",
    },
    price: [10, 12],
    tags: ["decafAvailable"],
  },
  {
    id: "chemex-duo",
    category: "degustation",
    name: { fr: "Chemex pour deux", en: "Chemex for two", hy: "Chemex երկուսի համար" },
    description: {
      fr: "Filtre Chemex, une carafe pensée pour deux.",
      en: "Chemex filter, one carafe made for two.",
      hy: "Chemex զտիչ՝ երկու հոգու համար նախատեսված։",
    },
    price: 12,
    unit: { fr: "pour 2", en: "for 2", hy: "2 հոգու համար" },
    tags: ["decafAvailable"],
  },
  {
    id: "flight",
    category: "degustation",
    name: {
      fr: "Flight dégustation — 3 origines",
      en: "Tasting flight — 3 origins",
      hy: "Համտեսի հավաքածու — 3 ծագում",
    },
    description: {
      fr: "Trois origines, trois profils, une dégustation guidée.",
      en: "Three origins, three profiles, one guided tasting.",
      hy: "Երեք ծագում, երեք բնութագիր, մեկ առաջնորդվող համտես։",
    },
    price: 15,
    tags: ["decafAvailable"],
  },
  {
    id: "cafe-de-la-semaine",
    category: "degustation",
    name: { fr: "Café de la semaine", en: "Coffee of the week", hy: "Շաբաթվա սուրճը" },
    description: {
      fr: "Un lot rare ou co-fermenté, en édition limitée.",
      en: "A rare or co-fermented lot, in limited release.",
      hy: "Հազվագյուտ կամ համատեղ խմորված լոտ՝ սահմանափակ քանակով։",
    },
    price: [9, 14],
    tags: ["decafAvailable"],
    featured: true,
  },

  // --- froid — Boissons froides ---
  {
    id: "cold-brew",
    category: "froid",
    name: { fr: "Cold brew", en: "Cold brew", hy: "Cold brew" },
    description: {
      fr: "Infusion à froid pendant 16 heures, douce et ronde.",
      en: "Cold-steeped for 16 hours, smooth and round.",
      hy: "16 ժամ սառը եփում, փափուկ և կլոր համ։",
    },
    price: 5.5,
    tempC: 4,
    tags: ["decafAvailable"],
  },
  {
    id: "nitro",
    category: "froid",
    name: { fr: "Nitro cold brew", en: "Nitro cold brew", hy: "Nitro cold brew" },
    description: {
      fr: "Cold brew infusé à l'azote, texture crémeuse.",
      en: "Cold brew infused with nitrogen, creamy texture.",
      hy: "Ազոտով հագեցած cold brew, կրեմային հյուսվածք։",
    },
    price: 6.5,
    tempC: 4,
    tags: ["decafAvailable"],
  },
  {
    id: "iced-latte",
    category: "froid",
    name: { fr: "Iced latte", en: "Iced latte", hy: "Iced latte" },
    description: {
      fr: "Espresso, lait et glace, en toute simplicité.",
      en: "Espresso, milk and ice, kept simple.",
      hy: "Էսպրեսո, կաթ և սառույց՝ պարզ ու համեղ։",
    },
    price: 6.0,
    tags: ["decafAvailable"],
  },
  {
    id: "espresso-tonic",
    category: "froid",
    name: { fr: "Espresso tonic", en: "Espresso tonic", hy: "Espresso tonic" },
    description: {
      fr: "Espresso sur tonic glacé, vif et pétillant.",
      en: "Espresso over iced tonic, bright and fizzy.",
      hy: "Էսպրեսո սառը տոնիկի հետ՝ թարմ ու փրփրացող։",
    },
    price: 6.5,
    tags: ["decafAvailable"],
  },
  {
    id: "ca-phe-sua-da",
    category: "froid",
    name: { fr: "Café vietnamien glacé", en: "Vietnamese iced coffee", hy: "Վիետնամական սառը սուրճ" },
    description: {
      fr: "Café robusta, lait concentré sucré, glaçons.",
      en: "Robusta coffee, sweetened condensed milk, ice.",
      hy: "Ռոբուստա սուրճ, քաղցրացված խտացրած կաթ, սառույց։",
    },
    price: 6.0,
  },
  {
    id: "affogato",
    category: "froid",
    name: { fr: "Affogato", en: "Affogato", hy: "Աֆոգատո" },
    description: {
      fr: "Glace vanille noyée d'un shot d'espresso chaud.",
      en: "Vanilla ice cream drowned in a hot espresso shot.",
      hy: "Վանիլային պաղպաղակ՝ տաք էսպրեսոյով ողողված։",
    },
    price: 6.5,
  },

  // --- signatures — Signatures CELSIUS ---
  {
    id: "sig-4",
    category: "signatures",
    name: {
      fr: "« 4 °C » — cold brew aux agrumes",
      en: '"4 °C" — citrus cold brew',
      hy: "«4 °C» — ցիտրուսային cold brew",
    },
    description: {
      fr: "Cold brew maison relevé de zestes d'agrumes.",
      en: "House cold brew brightened with citrus zest.",
      hy: "Cold brew՝ ցիտրուսային կեղևով համեմված։",
    },
    price: 6.5,
    tempC: 4,
  },
  {
    id: "sig-65",
    category: "signatures",
    name: {
      fr: "« 65 °C » — latte vanille & crème",
      en: '"65 °C" — vanilla cream latte',
      hy: "«65 °C» — վանիլային լատտե",
    },
    description: {
      fr: "Latte onctueux à la vanille et à la crème.",
      en: "Velvety latte with vanilla and cream.",
      hy: "Թավշյա լատտե՝ վանիլով և սերուցքով։",
    },
    price: 6.5,
    tempC: 65,
  },
  {
    id: "sig-93",
    category: "signatures",
    name: {
      fr: "« 93 °C » — espresso de la semaine",
      en: '"93 °C" — espresso of the week',
      hy: "«93 °C» — շաբաթվա էսպրեսո",
    },
    description: {
      fr: "L'origine du moment, servie en pur espresso.",
      en: "The current origin, served as a straight espresso.",
      hy: "Ընթացիկ ծագումը՝ մաքուր էսպրեսոյով մատուցված։",
    },
    price: 4.0,
    tempC: 93,
  },
  {
    id: "egg-coffee",
    category: "signatures",
    name: {
      fr: "Café aux œufs à la vietnamienne",
      en: "Vietnamese egg coffee",
      hy: "Վիետնամական ձվով սուրճ",
    },
    description: {
      fr: "Crème d'œuf battu et café robusta, recette vietnamienne.",
      en: "Whipped egg cream over robusta coffee, Vietnamese recipe.",
      hy: "Հարած ձվի կրեմ և ռոբուստա սուրճ՝ վիետնամական բաղադրատոմսով։",
    },
    price: 6.5,
  },

  // --- sans-cafe — Autour du café ---
  {
    id: "the",
    category: "sans-cafe",
    name: { fr: "Thés d'exception", en: "Fine teas", hy: "Ընտիր թեյեր" },
    description: {
      fr: "Sélection de thés fins, en feuilles entières.",
      en: "A selection of fine teas, whole leaf.",
      hy: "Նուրբ թեյերի ընտրանի՝ ամբողջական տերևներով։",
    },
    price: [5, 6],
  },
  {
    id: "infusion",
    category: "sans-cafe",
    name: { fr: "Infusions bio", en: "Organic herbal infusions", hy: "Օրգանական թուրմեր" },
    description: {
      fr: "Plantes et fleurs bio, sans caféine.",
      en: "Organic herbs and flowers, caffeine-free.",
      hy: "Օրգանական խոտաբույսեր և ծաղիկներ՝ առանց կոֆեինի։",
    },
    price: 4.5,
    tags: ["vegan"],
  },
  {
    id: "matcha-latte",
    category: "sans-cafe",
    name: { fr: "Matcha latte", en: "Matcha latte", hy: "Մաչա լատտե" },
    description: {
      fr: "Matcha cérémonial fouetté, lait vapeur.",
      en: "Whisked ceremonial-grade matcha, steamed milk.",
      hy: "Հարած ծիսակարգային մաչա, շոգեխաշված կաթ։",
    },
    price: 6.0,
  },
  {
    id: "golden-latte",
    category: "sans-cafe",
    name: { fr: "Golden latte (curcuma)", en: "Golden latte (turmeric)", hy: "Ոսկեգույն լատտե (քրքում)" },
    description: {
      fr: "Lait d'or au curcuma et épices douces.",
      en: "Golden milk with turmeric and warm spices.",
      hy: "Ոսկեգույն կաթ՝ քրքումով և մեղմ համեմունքներով։",
    },
    price: 5.5,
  },
  {
    id: "chai-latte",
    category: "sans-cafe",
    name: { fr: "Chaï latte", en: "Chai latte", hy: "Չայ լատտե" },
    description: {
      fr: "Thé noir épicé, lait vapeur, notes chaleureuses.",
      en: "Spiced black tea, steamed milk, warm notes.",
      hy: "Համեմունքային սև թեյ, շոգեխաշված կաթ, ջերմ երանգներ։",
    },
    price: 5.5,
  },
  {
    id: "chocolat-chaud",
    category: "sans-cafe",
    name: { fr: "Chocolat chaud", en: "Hot chocolate", hy: "Տաք շոկոլադ" },
    description: {
      fr: "Chocolat fondu au lait vapeur, texture gourmande.",
      en: "Melted chocolate with steamed milk, indulgent texture.",
      hy: "Հալված շոկոլադ շոգեխաշված կաթով, հարուստ հյուսվածք։",
    },
    price: 5.5,
  },

  // --- fraicheur — Fraîcheur ---
  {
    id: "citronnade",
    category: "fraicheur",
    name: { fr: "Citronnade maison", en: "Homemade lemonade", hy: "Տնական լիմոնադ" },
    description: {
      fr: "Citrons pressés, sucre fin, eau pétillante.",
      en: "Fresh-squeezed lemons, fine sugar, sparkling water.",
      hy: "Քամված կիտրոն, մանր շաքար, փրփրացող ջուր։",
    },
    price: 4.5,
    tags: ["vegan", "homemade"],
  },
  {
    id: "jus-presse",
    category: "fraicheur",
    name: { fr: "Jus pressé", en: "Fresh-pressed juice", hy: "Քամված հյութ" },
    description: {
      fr: "Fruits et légumes de saison, pressés à la minute.",
      en: "Seasonal fruit and vegetables, pressed to order.",
      hy: "Սեզոնային մրգեր և բանջարեղեն՝ պատվերով քամված։",
    },
    price: 5.5,
    tags: ["vegan"],
  },
  {
    id: "kombucha",
    category: "fraicheur",
    name: { fr: "Kombucha", en: "Kombucha", hy: "Կոմբուչա" },
    description: {
      fr: "Thé fermenté, léger et pétillant.",
      en: "Fermented tea, light and fizzy.",
      hy: "Խմորված թեյ՝ թեթև և փրփրացող։",
    },
    price: 5.0,
    tags: ["vegan"],
  },
  {
    id: "eau",
    category: "fraicheur",
    name: { fr: "Eau minérale", en: "Mineral water", hy: "Հանքային ջուր" },
    description: {
      fr: "Plate ou pétillante.",
      en: "Still or sparkling.",
      hy: "Սովորական կամ գազավորված։",
    },
    price: 3.0,
    tags: ["vegan"],
  },

  // --- douceurs — Douceurs maison ---
  {
    id: "croissant",
    category: "douceurs",
    name: { fr: "Croissant", en: "Croissant", hy: "Կրուասան" },
    description: {
      fr: "Pur beurre, feuilleté à la minute.",
      en: "All-butter, laminated fresh.",
      hy: "Զուտ կարագով, թարմ շերտավոր խմոր։",
    },
    price: 2.5,
    tags: ["homemade"],
  },
  {
    id: "pain-au-chocolat",
    category: "douceurs",
    name: { fr: "Pain au chocolat", en: "Pain au chocolat", hy: "Շոկոլադով բուլկի" },
    description: {
      fr: "Feuilleté pur beurre, deux bâtons de chocolat.",
      en: "All-butter pastry, two batons of chocolate.",
      hy: "Կարագով շերտավոր խմոր՝ երկու շոկոլադե ձողիկով։",
    },
    price: 2.8,
    tags: ["homemade"],
  },
  {
    id: "cruffin",
    category: "douceurs",
    name: { fr: "Cruffin", en: "Cruffin", hy: "Կրաֆին" },
    description: {
      fr: "Croissant et muffin, feuilleté et fourré.",
      en: "Croissant meets muffin, laminated and filled.",
      hy: "Կրուասանի և մաֆինի խաչասերում՝ շերտավոր ու լցոնված։",
    },
    price: 4.5,
    tags: ["homemade"],
  },
  {
    id: "babka",
    category: "douceurs",
    name: { fr: "Babka", en: "Babka", hy: "Բաբկա" },
    description: {
      fr: "Brioche tressée, marbrée au chocolat.",
      en: "Braided brioche, marbled with chocolate.",
      hy: "Հյուսված բրիոշ՝ շոկոլադե մարմարապատկերով։",
    },
    price: 4.5,
    tags: ["homemade"],
  },
  {
    id: "cheesecake",
    category: "douceurs",
    name: { fr: "Cheesecake", en: "Cheesecake", hy: "Չիզքեյք" },
    description: {
      fr: "Crémeux, base sablée, cuit au four.",
      en: "Creamy, baked, on a shortbread base.",
      hy: "Կրեմային, թխած, ավազահունց հիմքով։",
    },
    price: 6.0,
    tags: ["homemade"],
  },
  {
    id: "carrot-cake",
    category: "douceurs",
    name: { fr: "Carrot cake", en: "Carrot cake", hy: "Գազարով կեք" },
    description: {
      fr: "Moelleux à la carotte, glaçage au fromage frais.",
      en: "Moist carrot cake, cream cheese frosting.",
      hy: "Փափկամեջ գազարով կեք՝ կրեմային պանրի ծածկով։",
    },
    price: 5.5,
    tags: ["homemade"],
  },
  {
    id: "banana-bread",
    category: "douceurs",
    name: { fr: "Banana bread", en: "Banana bread", hy: "Բանանով հաց" },
    description: {
      fr: "Banane fondante, recette végane.",
      en: "Melting banana, vegan recipe.",
      hy: "Հալվող բանան՝ վեգան բաղադրատոմսով։",
    },
    price: 4.0,
    tags: ["homemade", "vegan"],
  },
  {
    id: "cookie",
    category: "douceurs",
    name: { fr: "Cookie", en: "Cookie", hy: "Cookie" },
    description: {
      fr: "Pépites de chocolat, cœur fondant.",
      en: "Chocolate chips, gooey center.",
      hy: "Շոկոլադի կտորներով, հալվող միջուկով։",
    },
    price: 3.0,
    tags: ["homemade"],
  },
  {
    id: "financier",
    category: "douceurs",
    name: { fr: "Financier", en: "Financier", hy: "Ֆինանսիե" },
    description: {
      fr: "Beurre noisette et amandes, sans gluten.",
      en: "Brown butter and almonds, gluten-free.",
      hy: "Խարբրած կարագ և նուշ, առանց գլյուտենի։",
    },
    price: 3.0,
    tags: ["homemade", "glutenFree"],
  },
  {
    id: "madeleines",
    category: "douceurs",
    name: { fr: "Madeleines", en: "Madeleines", hy: "Մադլեն" },
    description: {
      fr: "Petites coquilles moelleuses, zeste de citron.",
      en: "Soft little shells, a hint of lemon zest.",
      hy: "Փափուկ փոքրիկ խեցիներ՝ կիտրոնի կեղևի բույրով։",
    },
    price: 3.0,
    tags: ["homemade"],
  },

  // --- sale — Salé ---
  {
    id: "tartine-avocat",
    category: "sale",
    name: {
      fr: "Tartine avocat, pain au levain maison",
      en: "Avocado toast, house sourdough",
      hy: "Ավոկադոյով տոստ, տնական թթխմորով հաց",
    },
    description: {
      fr: "Avocat écrasé sur pain au levain maison.",
      en: "Mashed avocado on house sourdough.",
      hy: "Ջարդված ավոկադո՝ տնական թթխմորով հացի վրա։",
    },
    price: 10,
    tags: ["homemade", "vegan"],
  },
  {
    id: "tartine-saumon",
    category: "sale",
    name: { fr: "Tartine saumon", en: "Salmon toast", hy: "Սաղմոնով տոստ" },
    description: {
      fr: "Saumon fumé, pain au levain maison.",
      en: "Smoked salmon on house sourdough.",
      hy: "Ապխտած սաղմոն՝ տնական թթխմորով հացի վրա։",
    },
    price: 12,
    tags: ["homemade"],
  },
  {
    id: "tartine-houmous",
    category: "sale",
    name: {
      fr: "Tartine houmous & légumes",
      en: "Hummus & vegetable toast",
      hy: "Հումուսով և բանջարեղենով տոստ",
    },
    description: {
      fr: "Houmous maison, légumes de saison.",
      en: "House hummus, seasonal vegetables.",
      hy: "Տնական հումուս, սեզոնային բանջարեղեն։",
    },
    price: 9,
    tags: ["homemade", "vegan"],
  },
  {
    id: "focaccia",
    category: "sale",
    name: { fr: "Focaccia garnie", en: "Filled focaccia", hy: "Միջուկով ֆոկաչչա" },
    description: {
      fr: "Focaccia maison, garniture du jour.",
      en: "House focaccia, today's topping.",
      hy: "Տնական ֆոկաչչա՝ օրվա միջուկով։",
    },
    price: 8,
    tags: ["homemade"],
  },
  {
    id: "quiche",
    category: "sale",
    name: { fr: "Quiche du jour", en: "Quiche of the day", hy: "Օրվա կիշ" },
    description: {
      fr: "Pâte maison, garniture selon le marché.",
      en: "House pastry, filling based on the market.",
      hy: "Տնական խմոր, շուկայի համաձայն միջուկով։",
    },
    price: 9,
    tags: ["homemade"],
  },
  {
    id: "soupe",
    category: "sale",
    name: { fr: "Soupe du jour", en: "Soup of the day", hy: "Օրվա ապուր" },
    description: {
      fr: "Recette du jour, légumes de saison.",
      en: "Today's recipe, seasonal vegetables.",
      hy: "Օրվա բաղադրատոմս՝ սեզոնային բանջարեղենով։",
    },
    price: 7,
    tags: ["homemade"],
  },
  {
    id: "bowl",
    category: "sale",
    name: { fr: "Bowl végétarien", en: "Vegetarian bowl", hy: "Բուսակերական բոուլ" },
    description: {
      fr: "Céréales, légumes et légumineuses de saison.",
      en: "Grains, vegetables and legumes, seasonal.",
      hy: "Հացահատիկ, բանջարեղեն և հատիկաընդեղեն՝ սեզոնային։",
    },
    price: 12,
    tags: ["glutenFree"],
  },

  // --- formules — Formules ---
  {
    id: "petit-dej",
    category: "formules",
    name: { fr: "Petit-déjeuner", en: "Breakfast", hy: "Նախաճաշ" },
    description: {
      fr: "Boisson chaude et viennoiserie au choix.",
      en: "Hot drink and a pastry of your choice.",
      hy: "Տաք խմիչք և թխվածք՝ ըստ ընտրության։",
    },
    price: 7,
  },
  {
    id: "dejeuner",
    category: "formules",
    name: { fr: "Déjeuner", en: "Lunch", hy: "Ճաշ" },
    description: {
      fr: "Plat salé, boisson et douceur.",
      en: "Savoury dish, a drink and something sweet.",
      hy: "Աղի ուտեստ, խմիչք և աղանդեր։",
    },
    price: 16,
  },
  {
    id: "brunch",
    category: "formules",
    name: { fr: "Brunch du week-end", en: "Weekend brunch", hy: "Հանգստյան օրերի բրանչ" },
    description: {
      fr: "Formule complète, servie le week-end.",
      en: "The full spread, served on weekends.",
      hy: "Ամբողջական ընտրանի՝ հանգստյան օրերին։",
    },
    price: 24,
  },
];
